# Generated by Django 2.1.5 on 2019-01-15 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
